# https://docs.github.com/en/actions/reference/workflows-and-actions/metadata-syntax
name: 'minecraft-manifest'
description: 'GitHub Action that provides information about the Minecraft Manifest (ex. latest release or snapshot version)'
author: 'Mqxx'
branding:
  icon: 'file'
  color: 'green'

inputs:
  version: 
    description: |
      Version to get information for.

      Possible values:
      - 'latest-snapshot'
      - 'latest-release'
      - <valid_version> (ex. 1.21.11 or 26.1-snapshot-1)
      
    required: false
    default: 'latest-release'

  manifest-url:
    description: 'URL to the manifest API.'
    required: false
    default: 'https://piston-meta.mojang.com/mc/game/version_manifest_v2.json'

  if-version-is-invalid:
    description: |
      The desired behavior if the provided version is invalid.

      Possible values:
      - warn: Output a warning but do not fail the action
      - error: Fail the action with an error message
      - ignore: Do not output any warnings or errors, the action does not fail
    required: false
    default: 'warn'

outputs:
  raw-json:
    description: 'The raw manifest file parsed as JSON.'

  type:
    description: 'Type of the version.'
    
  latest-release-version:
    description: 'The latest release version.'

  latest-snapshot-version:
    description: 'The latest snapshot version.'

  versions:
    description: 'List of all available versions.'

  release-versions:
    description: 'List of all available release versions.'

  snapshot-versions:
    description: 'List of all available snapshot versions.'

  spril-fools-versions:
    description: 'List of all available april fools versions.'

  create-time:
    description: 'Time when the version was created/uploaded. (Based on the input version)'

  release-time:
    description: 'Time when the version was officially released. (Based on the input version)'

  package-url:
    description: 'Package URL of the version. (Based on the input version)'

  client-download-url:
    description: 'URL to download the client. (Based on the input version)'

  server-download-url:
    description: 'URL to download the server. (Based on the input version)'

  asset-index-url:
    description: 'URL thats points to the assets. (Based on the input version)'

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    INPUT_VERSION: ${{ inputs.version }}
    INPUT_MANIFEST_URL: ${{ inputs.manifest-url }}
    INPUT_IF_VERSION_IS_INVALID: ${{ inputs.if-version-is-invalid }}
